### ISSUE TITLE
How to load image directly to crop that image

### ISSUE THREAD

**Issue by jaygajjar40** [andyshora/angular-image-crop#5]
hi, well is there any way to just use image without uploading image ?
i mean i have image source for <img src="SOURCE"> and i want to crop that image, and in this plugin it is providing upload image button but i want to just crop image without uploading that image bcoz i already have image source/path

**Comment by pflopez** [comment]
Hi There, I know this issue is closed but I'm having a similar issue, which I think is what @jaygajjar40 meant..
Basically this plugin is hooked to a file upload input. Is there any way of instead of reading an image that way, just provide a url to a file directly to the directive, sort of original-image="OriginalImageUrl" ?

Hope it makes sense... thanks!
